{
 "title": "HeadlineCoach dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Principales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (increase(api_response_time_count[1m:60s]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Seconds per Status code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum[1m:1m])) by (status_code)  / sum(increase(api_summary_responses_count[1m:1m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request by Status code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(api_response_time_count[1m:60s]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request by Status code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(api_response_time_count[1m:60s]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Seconds per Endpoint",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum[1m:1m])) by (route,method)  / sum(increase(api_summary_responses_count[1m:1m])) by (route,method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request by Endpoint",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_count[1m:1m])) by(route, method)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request by Endpoint",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_count[1m:1m])) by(route, method)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Seconds per Method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum[1m:1m])) by (method)  / sum(increase(api_summary_responses_count[1m:1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request by Method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_bucket[1m:60s])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request by Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_bucket[1m:60s])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Jugadores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Requests a jugadores",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_count{route=~\"/jugadores.*\"}[1m:1m])) by(route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET jugadores",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/jugadores\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/jugadores\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET jugadores por equipo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/jugadoresEquipo/:idEquipo\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/jugadoresEquipo/:idEquipo\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET jugador",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/jugadores/:idJugador\",method=\"GET\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/jugadores/:idJugador\",method=\"GET\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "PUT jugador",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/jugadores/:idJugador\", method=\"PUT\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/jugadores/:idJugador\",method=\"PUT\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET jugadores antiguos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/jugadores/antiguos/:idEquipo/:semana\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/jugadores/antiguos/:idEquipo/:semana\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  { "title": "Equipos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Requests a equipos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_count{route=~\"/equipos.*\"}[1m:1m])) by(route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET equipos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/equipos\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/equipos\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET equipo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/equipos/:idEquipo\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/equipos/:idEquipo\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  { "title": "Ligas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Requests a ligas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_count{route=~\"/ligas.*\"}[1m:1m])) by(route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET ligas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/ligas/:id\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/ligas/:id\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET liga",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/ligas/usuario/:idUsuario\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/ligas/usuario/:idUsuario\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "POST ligas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/ligas\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/ligas\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "POST ligas/:idLiga",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/ligas/:idLiga\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/ligas/:idLiga\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET random liga",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/ligas/random/new\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/ligas/random/new\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET join liga",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/ligas/join/:idLiga\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/ligas/join/:idLiga\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  { "title": "Mercado", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Requests a mercado",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_count{route=~\"/mercado.*\"}[1m:1m])) by(route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST mercado pujar",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/mercado/pujar/:idLiga\", method=\"POST\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/mercado/pujar/:idLiga\", method=\"POST\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "POST mercado añadir",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/mercado/añadir/:idLiga\", method=\"POST\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/mercado/añadir/:idLiga\", method=\"POST\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "POST mercado aceptar oferta",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/mercado/aceptaroferta/:idLiga\", method=\"POST\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/mercado/aceptaroferta/:idLiga\", method=\"POST\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "POST mercado rechazar oferta",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/mercado/rechazaroferta/:idLiga\", method=\"POST\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/mercado/rechazaroferta/:idLiga\", method=\"POST\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  { "title": "Partidos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "Requests a partido",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 170 },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_count{route=~\"/partidos.*\"}[1m:1m])) by(route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET partido",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/partidos/:id\", method=\"GET\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/partidos/:id\", method=\"GET\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "PUT partido",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/partidos/:id\", method=\"PUT\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/partidos/:id\", method=\"PUT\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET partidos jornada",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/partidos/jornada/:jornada\", method=\"GET\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/partidos/jornada/:jornada\", method=\"GET\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET partidos equipo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/partidos/equipo/:idEquipo\", method=\"GET\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/partidos/equipo/:idEquipo\", method=\"GET\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET puntuaciones partido",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/partidos/puntuaciones/:idPartido\", method=\"GET\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/partidos/puntuaciones/:idPartido\", method=\"GET\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  { "title": "Plantillas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 } },
  {
   "title": "Requests a plantillas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 203 },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_count{route=~\"/plantillas.*\"}[1m:1m])) by(route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET plantilla",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/plantillas/:idLiga/:idUsuario\", method=\"GET\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/plantillas/:idLiga/:idUsuario\", method=\"GET\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "POST crear plantilla",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/plantillas/crear\", method=\"POST\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/plantillas/crear\", method=\"POST\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "POST update plantilla",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/plantillas/update\", method=\"POST\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/plantillas/update\", method=\"POST\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  { "title": "Puntuaciones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 227 } },
  {
   "title": "Requests a puntuaciones",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 228 },
   "targets": [
    {
     "expr": "sum(increase(api_response_time_count{route=~\"/puntuaciones.*\"}[1m:1m])) by(route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET puntuaciones jugador",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/puntuaciones/:idJugador\", method=\"GET\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/puntuaciones/:idJugador\", method=\"GET\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "GET puntuaciones jugador partido",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/puntuaciones/:idJugador/:semana\", method=\"GET\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/puntuaciones/:idJugador/:semana\", method=\"GET\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  {
   "title": "POST puntuaciones",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(api_summary_responses_sum{route=\"/puntuaciones\", method=\"POST\"}[1m:1m])) / sum(increase(api_summary_responses_count{route=\"/puntuaciones\", method=\"POST\"}[1m:1m]))",
     "legendFormat": "Media del tiempo de respuesta"
    }
   ]
  },
  { "title": "Usuarios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 } }
 ]
}