{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Increase By statusCode",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(rest_response_time_seconds_bucket[1m:1m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "By statusCode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rest_response_time_seconds_bucket) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Increase By endpoint",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(rest_response_time_seconds_bucket[1m:1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "By endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rest_response_time_seconds_bucket) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}