name: Build and push Docker images
on: 
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: elgohr/Publish-Docker-Github-Action@3.04  
        with:
          workdir: restapi
          name: uo271580/fantasyrestapi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          command: |
            sudo docker stop restapi
            sudo docker rm restapi
            sudo docker pull ghcr.io/uo271580/fantasyrestapi:latest
            sudo docker run -d -p 3000:3000 --net=host --name restapi ghcr.io/uo271580/fantasyrestapi:latest
