name: Build and push Docker images
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: elgohr/Publish-Docker-Github-Action@3.04  
        with:
          name: pablo268/myFantasy
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          command: |
            docker stop restapi
            docker rm restapi
            docker pull ghcr.io/pablo268/restapi:latest
            docker run -d -p 5000:5000 --net=host --name restapi ghcr.io/pablo268/restapi:latest