name: Build and push Docker images
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit-test-restapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: restapi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v3
  build-restapi:
    runs-on: ubuntu-latest
    needs: [unit-test-restapi]
    env:
      MONGO_DB_URI: ${{secrets.MONGO_DB_URI}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: elgohr/Publish-Docker-Github-Action@3.04  
        with:        
          workdir: restapi
          name: uo271580/fantasyrestapi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          buildargs: |
            MONGO_DB_URI
            JWT_SECRET
  build-webapp:
    runs-on: ubuntu-latest
    needs: [unit-test-restapi]
    env:
      REACT_APP_API_URI: ${{secrets.REACT_APP_API_URI}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          workdir: webapp
          name: uo271580/fantasywebapp
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          buildargs: REACT_APP_API_URI
  deploy-restapi:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [build-webapp, build-restapi]
    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          command: |
            sudo docker stop restapi
            sudo docker rm restapi
            sudo docker pull ghcr.io/uo271580/fantasyrestapi:latest
            sudo docker run -d -p 5000:5000 --net=host --name restapi ghcr.io/uo271580/fantasyrestapi:latest
  deploy-webapp:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [build-webapp, build-restapi, deploy-restapi]
    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          command: |
            sudo docker stop webapp
            sudo docker rm webapp
            sudo docker pull ghcr.io/uo271580/fantasywebapp:latest
            sudo docker run -d -p 8100:8100 --net=host --name webapp ghcr.io/uo271580/fantasywebapp:latest
            sudo docker image prune -f